[package]
name = "geph5-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyctx = "0.1.0"
anyhow = "1.0.80"
isocountry = "0.3.2"
serde={version="1", features=["derive"]}
smol = "2.0.0"
smol-timeout = "0.6.0"
smolscale = "0.4.4"
geph5-broker-protocol={path="../../libraries/geph5-broker-protocol"}
geph5-misc-rpc={path="../../libraries/geph5-misc-rpc"}
picomux={path="../../libraries/picomux"}
sillad={path="../../libraries/sillad"}
mizaru2={path="../../libraries/mizaru2"}
sillad-sosistab3={path="../../libraries/sillad-sosistab3"}
nanorpc-sillad={path="../../libraries/nanorpc-sillad"}
reqwest = {version="0.11.24", default-features=false, features=["rustls-tls"]}
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-async-std"] }
async-trait = "0.1.77"
nanorpc = "0.1.12"
thiserror = "1.0.57"
serde_json = "1.0.114"
rand = "0.8.5"
x25519-dalek = "2.0.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
stdcode = "0.1.14"
blake3 = "1.5.0"
argh = "0.1.12"
serde_yaml = "0.9.32"
futures-util = "0.3.30"
socksv5 = "0.3.1"
tachyonix = "0.2.1"
oneshot = "0.1.6"
clone-macro = "0.1.0"
ed25519-dalek = "2.1.1"
hex = "0.4.3"
nursery_macro = "0.1.0"
event-listener = "5.2.0"
blind-rsa-signatures = "0.15.0"
tap = "1.0.1"
