[package]
name = "geph5-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geph5-misc-rpc={path="../../libraries/geph5-misc-rpc"}
picomux={path="../../libraries/picomux"}
rand = "0.8.5"
sillad={path="../../libraries/sillad"}
smolscale = "0.4.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
geph5-broker-protocol={path="../../libraries/geph5-broker-protocol"}
nanorpc = "0.1.12"
nanorpc-sillad={path="../../libraries/nanorpc-sillad"}
async-trait = "0.1.77"
blake3 = "1.5.0"
async-io = "2.3.1"
