[workspace]

members = [
    "libraries/*",
    "binaries/*"
]
resolver = "2"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
opt-level = 1

[profile.dev.package.num-bigint-dig]
opt-level = 3


[profile.release-dbg]
inherits = "dev"
opt-level = 3 
