[package]
name = "geph5-client-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
csv = "1.3.0"
dirs = "5.0.1"
eframe = {version="0.27.2", default-features=false, features=["wgpu", "x11"]}
egui = "0.27.2"
moka = {version="0.12.5", features=["sync"]}

once_cell = "1.19.0"
smol_str = {version="0.2.1", features=["serde"]}
tap = "1.0.1"
