[package]
name = "mizaru2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = {version="1.5.1", features=["serde"]}
blind-rsa-signatures = "0.15.0"
rand = "0.8.5"
stdcode = "0.1.14"
serde = {version="1.0.200", features=["derive", "rc"]}
anyhow = "1.0.82"
rayon = "1.10.0"
