[package]
name = "sillad-sosistab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.7"
blake3 = "1.5.0"
chacha20poly1305 = "0.10.1"
rand = "0.8.5"
x25519-dalek = {version="2.0.1", features=["serde"]}
sillad={path="../sillad"}
futures-util = "0.3.30"
pin-project = "1.1.4"
smallvec = "1.13.1"
async-trait = "0.1.77"
tap = "1.0.1"
tracing = "0.1.40"
tachyonix = "0.2.1"
smolscale = "0.4.4"
async-task = "4.7.0"
async-executor = "1.8.0"
serde = {version="1.0.197", features=["derive"]}
hex = "0.4.3"
