[package]
name = "geph5-exit"
version = "0.1.0"
edition = "2021"
license="MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geph5-broker-protocol={path="../../libraries/geph5-broker-protocol"}
sillad={path="../../libraries/sillad"}
sillad-sosistab3={path="../../libraries/sillad-sosistab3"}
picomux={path="../../libraries/picomux"}
async-trait = "0.1.80"
nanorpc = "0.1.12"
thiserror = "1.0.59"
smolscale = "0.4.4"
futures-util = "0.3.30"
async-io = "2.3.2"
once_cell = "1.19.0"
serde = "1.0.200"
serde_json = "1.0.116"
serde_yaml = "0.9.34"
argh = "0.1.12"
anyhow = "1.0.82"
tracing = "0.1.40"
smol = "2.0.0"
rand = "0.8.5"
reqwest = {version="0.12.4", default-features=false, features=["rustls-tls"]}
isocountry = "0.3.2"
ed25519-dalek = "2.1.1"
blake3 = "1.5.1"
tracing-subscriber = "0.3.18"
tap = "1.0.1"
geph5-misc-rpc={path="../../libraries/geph5-misc-rpc"}
stdcode = "0.1.14"
x25519-dalek = "2.0.1"
hex = "0.4.3"
nursery_macro = "0.1.0"
moka = {version="0.12.7", features=["future"]}
tachyonix = "0.2.1"
mizaru2={path="../../libraries/mizaru2"}
governor = "0.6.3"
quanta = "0.12.3"
sysinfo = "0.30.11"
atomic_float = "1.0.0"
fastrand = "2.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
