[package]
name = "async-rw-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = {version="0.3.30", features=["io"]}
recycle-box = "0.2.0"

[dev-dependencies]
pollster="0.3"
