[package]
name = "nanorpc-sillad"
version = "0.1.0"
edition = "2021"

[dependencies]
sillad = { path = "../sillad" }
async-trait = "0.1.80"
nanorpc = "0.1.12"
serde_json = "1.0.116"
thiserror = "1.0.59"
anyhow = "1.0.82"
futures-util = { version = "0.3.30", features = ["io"] }
async-executor = "1.11.0"
